name: Deploy to Server

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v2
        with:
          name: release-version

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /deployments/niftytools
            export RELEASE_VERSION=$(cat release_version.txt)
            sed -i "s/BACKEND_VERSION=.*/BACKEND_VERSION=$RELEASE_VERSION/" .env
            sed -i "s/USER_FRONTEND_VERSION=.*/USER_FRONTEND_VERSION=$RELEASE_VERSION/" .env
            sed -i "s/ADMIN_FRONTEND_VERSION=.*/ADMIN_FRONTEND_VERSION=$RELEASE_VERSION/" .env
            docker-compose up -d
            docker image prune -f
            docker container prune -f